### ISSUE TITLE
Version Check Needs Revision

### ISSUE THREAD

**Issue by kylegrieder** [supermamon/Reposi3#1]
Hey There, 

I use your repo template for my own personal github repo. I'm not at all proficient enough in js, html, or css for any of it. I can package my themes/tweaks and push my updates to github, and thats about it. 

I noticed, after iOS 10 came out, the version check doesn't seem to be working quite right. I'm guessing the fault lies somewhere in depictions/js/ios_version_check.js. It seems like the check is registering "iOS 10" and a version less than 7(probably some form of "iOS 1". 

If you could fix the js, that would be incredibly helpful. 

Thanks for making this template.

**Comment by kylegrieder** [comment]
Also, this is a separate issue, but maybe you can help me out: For some reason, my contact information doesn't show up at the bottom of my depic. github.com/kgfromthemv/kgfromthemv.github.io

**Comment by EthanRDoesMC** [comment]
can confirm, people are getting confused

**Comment by supermamon** [comment]
I'm working on an update. In the meantime, you can hide the compatibility check alert by editing depictions/index.html. Find the line that says:

```
if(res==0)` {$(element).hide()}
```
and change it to 
```
res=0;
if(res==0) {$(element).hide()}
```

**Comment by supermamon** [comment]
@kgfromthemv, your problem seems to be on because of your repo.xml file which is not a valid xml.
```
<url>https://www.reddit.com/message/compose?to=kgfromthemv&subject=</url>
```
should be 
```
<url>https://www.reddit.com/message/compose?to=kgfromthemv&amp;subject=</url>
```

**Comment by kylegrieder** [comment]
@supermamon I fixed the url in my repo.xml and it worked. Thanks.

**Comment by DGh0st** [comment]
@kgfromthemv @EthanRDoesMC There are two ways of fixing the version check.

First way is to fix it by parsing the strings to integers when you return the bits in parseVersionString and also parse to integers when you create osVersion.

Second way is to just parse to integers in the comparison function.

@supermamon I requested for a pull request with the first method.

**Comment by supermamon** [comment]
Fixed with @DGh0st's pull request. [b48d4b4](https://github.com/supermamon/Reposi3/commit/b48d4b48e6ba730a5bd9687db1582eafb9263f7e)
