### ISSUE TITLE
Repo shows updates always

### ISSUE THREAD

**Issue by s8ngyu** [supermamon/Reposi3#10]
My first tweak(LiveFish) is okay. But when I add more tweak, then Cydia always show updates even I updated.

How can I fix this?

**Comment by supermamon** [comment]
This largely depends on how you generate your `Packages` file. Cydia is detecting that there are differences between the hashes on the `Packages` file and the calculated hashes of the `.deb` files. Are you editing the file manually? Or using a script/program to do it for you?

**Comment by s8ngyu** [comment]
Thank you for reply. I'm using NotePad++ on Windows 10 to edit `Packages` file

**Comment by supermamon** [comment]
Ok. My recommendation is try the following

* Make sure your Packages file has Unix (LF) line endings instead of Windows (CR/LF)
* or try https://github.com/mstg/scanpkg to build it for you. 
* or use dpkg-scanpackages by installing WSL (since you’re on Win10) or a VM (using VirtualBox, etc)

**Comment by s8ngyu** [comment]
I'm using Win10 on BootCamp. Sould I use macOS? my `Packages` file has already Unix line endings.

**Comment by supermamon** [comment]
Oh, since you already have MacOS, you should be able to run `dpkg-scanpackages`. See step 3 on the README file.

**Comment by s8ngyu** [comment]
`Last login: Sun Jul 29 12:49:14 on console
Kwonui-MacBook-Pro:~ ksg$ ls
Creative Cloud Files	Downloads		Music
Desktop			Library			Pictures
Documents		Movies			Public
Kwonui-MacBook-Pro:~ ksg$ cd Documents/GitHub/nightly/
Kwonui-MacBook-Pro:nightly ksg$ dpkg
-bash: dpkg: command not found
Kwonui-MacBook-Pro:nightly ksg$ dpkg-scanpackages -m ./debs > Packages
-bash: dpkg-scanpackages: command not found
Kwonui-MacBook-Pro:nightly ksg$ 
`

What should I do to use dpkg on macOS?

**Comment by s8ngyu** [comment]
Solved. I installed dpkg. Thank you for reply and help me.
