### ISSUE TITLE
Failed to load depiction

### ISSUE THREAD

**Issue by s8ngyu** [supermamon/Reposi3#11]
I changed Oh snap!  The package you are tying to view is not hosted on this repository. to Error! Failed to load depiction. and I uploaded 4 tweaks.

- LiveFish
- Jileumsin
- iWallX
- Sidia

and I made depictions for them.

LiveFish and Jileumsin load depictions well, but iWallX and Sidia can't load depiction. I checked the url many times.

How can I fix this?

**Comment by supermamon** [comment]
Check your xml files. They must be valid xml syntax.

**Comment by s8ngyu** [comment]
Sorry, I'am a beginner. Can you explain it more easily?

**Comment by supermamon** [comment]
Go [here](https://codebeautify.org/xmlvalidator).
Paste the contents of your info.xml file for iWallX then click Validate.
It should show `Valid XML`.

Do the same for Sidia.

**Comment by s8ngyu** [comment]
Thank you. Solved
