### ISSUE TITLE
Tweaks wont show.

### ISSUE THREAD

**Issue by ghost** [supermamon/Reposi3#12]
I did everything correctly, but when I add a second tweak it doesn't show.

**Comment by supermamon** [comment]
Please explain what do you mean by "it doesn't show"

**Comment by ghost** [comment]
It won’t show on Cydia.

**Comment by supermamon** [comment]
Are you using `gh-pages` branch to publish your repo? If you do, you need to merge the updates from `master` to `gh-pages`.

**Comment by ghost** [comment]
I’m not using ‘gh-pages’, I’m publishing with ‘master’

**Comment by supermamon** [comment]
Ok. Something's caching your Packages.bz2. When I [download it](https://hang3r.github.io/Packages.bz2), and extract manually, it only contains 1 tweak. Either way this isn't an issue with Reposi3. Sorry I couldn't help.

**Comment by viggou** [comment]
Did you remember to rebuild your Packages file?
