### ISSUE TITLE
Unable to set minimum iOS in info.xml of depiction. 

### ISSUE THREAD

**Issue by ghost** [supermamon/Reposi3#14]
In info.xml, it says to specify `<maxiOS>`. The thing is that the tweak I want to host needs 11.0 and up, but all I'm able to put is the max iOS (11.3.1). So when someone with, for example, iOS 10 sees the tweak, the depiction makes it look like the tweak is compatible with their version. Any way to change this?

**Comment by supermamon** [comment]
have you tried to put `<miniOS>`?

**Comment by ghost** [comment]
Ok. Now it works. Thanks for the help, but I suggest you add `<miniOS>` to the template info file.
