### ISSUE TITLE
How to place screenshots in a different location then default. 

### ISSUE THREAD

**Issue by VanishingTacos** [supermamon/Reposi3#16]
It seems the default location is to place the screen shots  bundled in with the package

`source" :"package>screenshots>screenshot"`

I was wondering if I could and how I could place the screen shots into a different location. 

I.E.

`source" :"folder>bundleid>screenshots>screenshot"`

**Comment by supermamon** [comment]
the `source` value defines how to extract the list of screenshots from the `info.xml`, not the path of the screenshot file if that’s what you’re saying. The `<image>‘ node on `info.xml` is relative to the `/depictions/bundleid/screenshots/` folder. If you want to save your screenshots to another folder, you can do it by putting the path in the `<image>` node.  

Does this help?

**Comment by VanishingTacos** [comment]
I changed:

`.attr("src",bundleid+'/screenshots/'+$(data).find('image').text())`

to 

`.attr("src",'custom_folder/'+bundleid+'/screenshots/'+$(data).find('image').text())`

That fixed it for me

**Comment by supermamon** [comment]
good to know you figured that out. closing this now.
