### ISSUE TITLE
How to trigger no screen shot for this package 

### ISSUE THREAD

**Issue by yaf3i** [supermamon/Reposi3#17]
```
var contentBlocks = 	{
        "#screenshotsList"	: 
			{"type":"custom"  
				,"source" :"package>screenshots>screenshot"
				,"render" : function(element,source){
				console.log($(source).size());
					if ($(source).size()==0) {
						$(element).append( $("<div class='alert alert-danger'>The aren't any screenshots for this package</div>") ); 
						return;
```

**Comment by supermamon** [comment]
You can do that by not listing any screenshots on the `info.xml` file. Example is this [info.xml](https://github.com/supermamon/Reposi3/blob/master/depictions/com.supermamon.oldpackage/info.xml) file. 

[Here’s](https://supermamon.com/Reposi3/depictions/screenshots.html?p=com.supermamon.oldpackage) how it looks like.

**Comment by yaf3i** [comment]
thanks for fast reply </3
its worked !!

**Comment by yaf3i** [comment]
but the change log button will disappeared !

**Comment by supermamon** [comment]
got it. will fix that soon.

**Comment by yaf3i** [comment]
Thanks for you job,
one more question is there any way to show [this](https://supermamon.com/Reposi3/depictions/screenshots.html?p=com.supermamon.oldpackage) when u press the screenshots link

**Comment by supermamon** [comment]
The `Screenshots` link is designed to be hidden when there are no screenshots defined in `info.xml`. But it you want to force it to always show, comment out or delete [these](https://github.com/supermamon/Reposi3/blob/5ee5e56ab1f32f845ea0a7d86a7b97dae28a4e4c/depictions/index.html#L69-L71) lines.
