### ISSUE TITLE
is there any way to add gif or video at screenshots page ?

### ISSUE THREAD

**Issue by yaf3i** [supermamon/Reposi3#18]

**Comment by supermamon** [comment]
this template only allows images (including gifs). videos are not supported. you would need to customize by yourself if you need videos.

**Comment by yaf3i** [comment]
gifs not working

**Comment by supermamon** [comment]
yes they do. i tested that. here's a sample `screenshots` node for `info.xml` 

```xml
	<screenshots>
		<screenshot>
			<description>A GIF</description>
			<image>giphy.gif</image>
		</screenshot>
	</screenshots>
```
