### ISSUE TITLE
How to use ios_version_check.js in independent depiction

### ISSUE THREAD

**Issue by mohdalyahri** [supermamon/Reposi3#19]
I have used your depiction on my GitHub repo , and shifted to private repo as GitHub is static hosting service.
So, I wanna use your [ios_version_check.js](https://github.com/supermamon/Reposi3/blob/master/depictions/js/ios_version_check.js) on my custom deception.
your script works along with `Get` from `.xml` file. Can you guide me how to make it work on my page.?

Thanks in advance

**Comment by supermamon** [comment]
>  `function ios_version_check(minIOS,maxIOS,otherIOS,callBack)`

- returns
  - `-1 ` if not compatible
  - `0` if iOS version cannot be detected. `callback` will not be called.
  - `1` if compatible
- `minIOS` and `maxIOS` are pretty much self explanatory.
- `otherIOS` can be either "unsupported" or "unconfirmed". This is used when the device iOS version does not fall within `minIOS` and `maxIOS`.
- `callback` is the function to call after version check is done. requires 2 arguments - `message` and `isbad`.
  - `message` is the description returned by the function about it's version compatibility
  - `isbad` is the return value as described above

hope this helps.
