### ISSUE TITLE
Night mode 

### ISSUE THREAD

**Issue by Wh0ba** [supermamon/Reposi3#21]
Can you please add night/dark mode support

**Comment by favna** [comment]
You could simply import a dark bootstrap theme, for example [darkly from bootswatch](https://bootswatch.com/darkly/)

That said, the currently bootswatch versions do rely on Bootstrap 4 so that upgrade would be required too.

**Comment by aklef** [comment]
Bump - I would love to see this

**Comment by supermamon** [comment]
Added in 9185c4e.

**Comment by aklef** [comment]
Beautiful! Well done
