### ISSUE TITLE
How can I link the depiction page your tweak's control file in Windows?

### ISSUE THREAD

**Issue by 10Meisterbaelle** [supermamon/Reposi3#26]

**Comment by supermamon** [comment]
It's the same whether or not you're using Windows. See this sample https://github.com/supermamon/SpotWhite/blob/master/control

**Comment by 10Meisterbaelle** [comment]
But how do I extract and build my deb file?

**Comment by supermamon** [comment]
sorry, that's outside of the scope of this repo. try seeking assistance from the folks at r/jailbreakdevelopers
