### ISSUE TITLE
#packageHeader doesn't hide in Cydia

### ISSUE THREAD

**Issue by Nosskirneh** [supermamon/Reposi3#3]
`depictions/index.html:30`:

				,"render":function(element,source){
					if (navigator.userAgent.search(/Cydia/) == -1) {
						$(element).show();
					}

Doesn't work as intended for me (I suppose the package header are not supposed to be visible in Cydia, but everywhere else). Instead I have to fiddle around with `@media` queries :/

Not sure if this is to any use but using Cydia version 1.1.30.

**Comment by supermamon** [comment]
Fixed with commit e28299131e3858995daee1b3badeb2e666be801d
