### ISSUE TITLE
One package isn't found while the rest is

### ISSUE THREAD

**Issue by Nosskirneh** [supermamon/Reposi3#5]
Hmm, this is really weird and I can not figure out why. Maybe you have some insight?

[ProperLockGestures](https://andreashenriksson.se/repo/depictions/?p=se.nosskirneh.properlockgestures) works perfectly, but [PlexAutoRemote](https://andreashenriksson.se/repo/depictions/?p=se.nosskirneh.plexautoremote) does not. The files are there though.

I'm guessing [this](https://github.com/supermamon/Reposi3/blob/master/depictions/index.html#L136) is where the issue is:
```
        $.ajax({
            type    : "GET",
            dataType: "xml",
            url     : (bundleid+"/info.xml"),
            success : function(xml){
				document.title = $(xml).find("package>name").text();
            	data_loader_engine(contentBlocks,xml)

            },
			cache   : false,
            error: function() {
                $("#packageError").show();
				$("#packageInformation").hide();
            }
        }); //ajax
```

I'm not used with javascript, so you're probably more up for the fight.

----

Anyway, the files are in place with correct permissions as seen below (since the same permissions works for ProperLockGestures).
```
/srv/http/repo/depictions » la                                                      user@Server
total 60K
-rw-r--r-- 1 root  root  3.7K Mar  8 16:17 changelog.html
-rw-r--r-- 1 root  root  7.5K Apr 26 12:07 index.html
drwxr-xr-x 2 root  root  4.0K Mar  2 12:52 js
-rw-r--r-- 1 root  root  3.9K Mar  8 16:17 screenshots.html
drwxr-xr-x 2 root  root  4.0K Mar  9 12:26 se.nosskirneh.ccnoscroll
drwxr-xr-x 2 root  root  4.0K Mar  2 16:51 se.nosskirneh.cdc
drwxr-xr-x 3 root  root  4.0K Mar 20 21:48 se.nosskirneh.customlockscreenduration
drwxr-xr-x 2 root  root  4.0K Apr 11 15:12 se.nosskirneh.disabledtext
drwxr-xr-x 2 root  root  4.0K May  8 10:58 se.nosskirneh.plexautoremote
drwxr-xr-x 2 root  root  4.0K May  6 21:05 se.nosskirneh.properlockgestures
drwxr-xr-x 3 root  root  4.0K Mar  2 17:02 se.nosskirneh.spotifyofflineswitch
drwxr-xr-x 3 root  root  4.0K Mar  2 16:50 se.nosskirneh.spotifyswitches
drwxr-xr-x 2 root  root  4.0K Mar 16 07:10 se.nosskirneh.swishspeedup
-rw-r--r-- 1 root  root   568 Mar  8 16:17 style.css
------------------------------------------------------------
/srv/http/repo/depictions » la se.nosskirneh.plexautoremote                         user@Server
total 8.0K
-rw-r--r-- 1 root root 433 May  8 10:58 changelog.xml
-rw-r--r-- 1 root root 939 May  8 11:05 info.xml
------------------------------------------------------------
/srv/http/repo/depictions » la se.nosskirneh.properlockgestures                     user@Server
total 8.0K
-rw-r--r-- 1 root root  717 May  7 21:06 changelog.xml
-rw-r--r-- 1 root root 1.1K May  8 11:07 info.xml
```

The content of the faulty package's `info.xml` is shown correct when I transfer it to ProperLockGestures' `info.xml`. I should also add that before pushing version 0.0.2 of PlexAutoRemote, the page was loaded. Really weird.

Any ideas?

Edit:

Changed all permissions to 755, didn't change anything.

It gives me 401 Unauthorized when trying to load the page. When I browse to these files manually, it's no problems at all (?).
```
jquery.min.js:4 GET https://andreashenriksson.se/repo/repo.xml?_=1494241499643 401 (Unauthorized)

/repo/depictions/se.nosskirneh.plexautoremote/info.xml?_=1494240947580 Failed to load resource: the server responded with a status of 401 (Unauthorized)

/repo/repo.xml?_=1494240947581 Failed to load resource: the server responded with a status of 401 (Unauthorized)

style.css Failed to load resource: the server responded with a status of 401 (Unauthorized)
```

Edit 2:
Probably not an error in Reposi3 but rather somewhere in my nginx/php-fpm config :/

**Comment by supermamon** [comment]
(super late response, sorry)
I wanted to ask if you were able to fix this but looking at your repo, it seems not yet.
I download your xml files and tried on my side but they do load. Not sure what's causing the issue at this point.

Have you tried re-creating the se.nosskirneh.plexautoremote folder?

**Comment by Nosskirneh** [comment]
Had totally forgot about this. I barely use the repo anymore, and I doubt that anyone even uses PlexAutoRemote too. Since you tried it on your end and it didn't work, it's probably something with my nginx config or similar. Thanks for looking into it at least!
