### ISSUE TITLE
No index files let me change "brought to you by Reposi3" or am I just looking in the wrong places?

### ISSUE THREAD

**Issue by ghost** [supermamon/Reposi3#9]
Whenever I put a tweak in the Featured Packages section of index.html, and I click "More Info", it shows the tweak depiction but under the tweak name it shows "brought to you by Reposi3". How can I change this and is it even possible?

<img width="439" alt="screen shot 2018-07-28 at 8 29 55 pm" src="https://user-images.githubusercontent.com/41697585/43361712-530fa2b0-92a5-11e8-8ce1-5fb0ce654018.png">

**Comment by ghost** [comment]
Nevermind, found where I can change it

**Comment by supermamon** [comment]
Ok. I’ll probably make that customizable or remove it entirely. I’ll keep this open until I do that.

**Comment by ghost** [comment]
oh ok.

**Comment by supermamon** [comment]
Closed by 7617280
